### ISSUE TITLE
Erratic performace on RPi Zeros

### ISSUE THREAD

**Issue by netham45** [marqs85/gamecon_gpio_rpi#5] opened 2019-11-23 10:38 UTC
I'm having issues with N64 controllers with the gamecon_gpio_rpi driver. I'm getting erratic input on the analog stick and it randomly presses a few of the buttons a couple times a second. If I hold the buttons they stay held and other buttons work perfectly.

I'm using an RPi Zero W. I've had this working before, I'm not sure what's different. I've verified the CPU scaler governor is set to performance, I've tried locking the frequencies at 700 and 1000MHz in the config.txt and verified it's holding so I don't think it's a CPU freq issue.

I've also tried another Zero W, I'm getting the same results. Last time I had it working was in January this year, I tried the builds of Raspbian that were released at the time with no change. I also tried disabling BT and ensuring that I had the minimum kernel modules and services running that I need to get into the device.

The last time I had it working I was building v 1.3 from source. I've tried 1.4 on the latest kernel, and 1.3 on the kernel included with '2018-11-13-raspbian-stretch-lite'.

**Comment by netham45** [comment] 2019-11-23 10:42
I've also tried the builds installed by the official RetroPie release, and installing through retropie-setup on the latest Raspbian, they both gave me the same results.

**Comment by lewilou22** [comment] 2024-09-27 00:56
any fix? im having the same issue here!!

**Comment by marqs85** [comment] 2024-09-30 17:14
The N64/GC driver was developed and tested way back on first 2 RPi models. The code asynchronously samples data from the wire into a buffer and is reliant on GPIO reads taking place at somewhat fixed interval. For whatever reason this does not seem to work consistently on newer models / kernels. I can try to look into this at some point and see e.g. if stop bit could be detected reliably which could help invalidating bad reads.

**Comment by lewilou22** [comment] 2024-09-30 18:31
Thank you for the response.

I can test anything if needed.

My project is a Pi Zero 2 inside of the N64 controller with a 2 inch screen above the start button .
This would be the final step to get it all working :)

**Comment by marqs85** [comment] 2024-10-08 21:24
The root cause was identified (samplebuffer not completely zeroed) and fixed in 8332c9c. A pre-built deb package for v1.5 is found [here](http://www.infocult.com/m/tmp/gamecon-gpio-rpi_1.5.deb).

The read should be stable now, but robustness may be increased further with the following if needed:
* echo "performance" > /sys/devices/system/cpu/cpufreq/policy0/scaling_governor
* add "disable_l2cache=1" into /boot/config.txt

**Closed by marqs85** 2024-10-08 21:24 UTC

**Comment by lewilou22** [comment] 2024-10-08 22:41
Thank you its working

**Comment by marqs85** [comment] 2024-10-09 20:19
The .deb is now also available on the releases page with naming and structure matching earlier releases.
